let start = $(".navItem").css("color", "white")
let second = $("#nav").css("background-color", "#145")
let third = $("li:even").css("background-color", "#ccc")
let fourth = $("li:odd").css("background-color", "#aaa")
let fifth = $("#myInput").val("Lincoln Roberts")